ARG PLATFORM
FROM --platform=linux/${PLATFORM} amazoncorretto:17

COPY ./agent/jmx_prometheus_javaagent-1.2.0.jar /opt/jmx_prometheus_javaagent-1.2.0.jar
COPY ./agent/config.yaml /opt/config.yaml
ENV JAVA_TOOL_OPTIONS="-javaagent:/opt/jmx_prometheus_javaagent-1.2.0.jar=9404:/opt/config.yaml $JAVA_OPTS"
COPY ./target/hello.jar /app/demo.jar
# WORKDIR /app
EXPOSE 8080
ENTRYPOINT ["java", "-jar", "/app/demo.jar"]